name: ecommerce_store_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ^3.5.4
dependencies:
  animated_splash_screen: ^1.3.0
  card_swiper: ^3.0.1
  cloud_firestore: ^5.5.0
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  dynamic_height_grid_view: ^0.0.4
  fancy_shimmer_image: ^2.0.3
  firebase_auth: ^5.3.3
  firebase_core: ^3.8.0
  firebase_storage: ^12.3.6
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_stripe: ^11.3.0
  fluttertoast: ^8.2.8
  google_sign_in: ^6.2.2
  iconforest_ternav_icons_light: ^1.0.0+1
  iconly: ^1.0.1
  image_picker: ^1.1.2
  ionicons: ^0.2.2
  localization: ^2.1.1
  provider: ^6.0.5
  shared_preferences: ^2.3.3
  shimmer: ^3.0.0
  uuid: ^4.5.1
  win32: ^5.8.0
dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/images/profile/
    - assets/images/bag/
    - assets/images/banners/
    - assets/images/categories/
