// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0MDddkh6il0uvVw0QpsI6s-Vfuui_t6Y',
    appId: '1:392533156674:web:b259b898fd41675af09edb',
    messagingSenderId: '392533156674',
    projectId: 'shopsmart-ecommerce-app',
    authDomain: 'shopsmart-ecommerce-app.firebaseapp.com',
    storageBucket: 'shopsmart-ecommerce-app.appspot.com',
    measurementId: 'G-M3TPZQ2E7C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWgk1hE12TBdEh5ba09uJ4YWste5KP9zM',
    appId: '1:392533156674:android:b0dc117d7a6c233bf09edb',
    messagingSenderId: '392533156674',
    projectId: 'shopsmart-ecommerce-app',
    storageBucket: 'shopsmart-ecommerce-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAeEDHFBHffOhIkXu39bS6lhN9XKR8KnM',
    appId: '1:392533156674:ios:6ea4fd8ccbd70bbff09edb',
    messagingSenderId: '392533156674',
    projectId: 'shopsmart-ecommerce-app',
    storageBucket: 'shopsmart-ecommerce-app.appspot.com',
    iosBundleId: 'com.example.ecommerceStoreApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAeEDHFBHffOhIkXu39bS6lhN9XKR8KnM',
    appId: '1:392533156674:ios:6ea4fd8ccbd70bbff09edb',
    messagingSenderId: '392533156674',
    projectId: 'shopsmart-ecommerce-app',
    storageBucket: 'shopsmart-ecommerce-app.appspot.com',
    iosBundleId: 'com.example.ecommerceStoreApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0MDddkh6il0uvVw0QpsI6s-Vfuui_t6Y',
    appId: '1:392533156674:web:5178061e4c3d2e71f09edb',
    messagingSenderId: '392533156674',
    projectId: 'shopsmart-ecommerce-app',
    authDomain: 'shopsmart-ecommerce-app.firebaseapp.com',
    storageBucket: 'shopsmart-ecommerce-app.appspot.com',
    measurementId: 'G-36YEGH0NRC',
  );
}
